site_name: Slin Notes
site_url: https://notes.slin.com

site_description: MkDocs Bootstrap Theme
site_author: Tom Christie & Dougal Matthews

repo_name: 'SlinNotes'
repo_url: 'https://github.com/dxslin/SlinNotes'
edit_uri: 'tree/main/docs/'


nav:
    - 'Android':
        - '概述': Android/index.md
    - '帮助': help/

#https://squidfunk.github.io/mkdocs-material/getting-started/
theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  logo: ../dxslin_github_icon.jpg
  features:
    - navigation.tabs
  font:
    code: Jetbrains Mono
   

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list

plugins:
  - search
  - git-revision-date-localized:
      type: date

copyright: Copyright &copy; 2021 <a href="https://https://github.com/dxslin">dxslin</a>.