site_name: Slin笔记文库
site_url: https://notes.slin.com

site_description: 笔记仓库，以此替换网易云笔记
site_author: dxslin

repo_name: 'SlinNotes'
repo_url: 'https://github.com/dxslin/SlinNotes'
edit_uri: 'tree/main/docs/'

#目录，修改或者新增文件，需要添加到此处
nav:
    - '首页':
        - '概述': index.md
        - '帮助': 
            - 'Mkdocs使用说明': help/1. Mkdocs.md
            - 'Typora使用说明': help/2. Typora.md
            - 'PicGo使用说明': help/3. PicGo.md
            - 'Mermaid(流程图绘制)': help/4. Mermaid.md
    - 'Android':
        - '概述': Android/index.md
        - 'Jetpack': 
            - 'ViewModel': Android/Jetpack/6. ViewModel.md

    

#https://squidfunk.github.io/mkdocs-material/getting-started/
theme_dir: theme
theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  logo: assets/img/dxslin_github_icon.jpg
  features:
    - navigation.tabs
  font:
    code: Jetbrains Mono
    
# 自定义配置样式表
extra_css:
    - assets/css/extra.css
    
extra_javascript:
#    - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.jss
    - https://cdn.bootcdn.net/ajax/libs/mermaid/8.10.2/mermaid.min.js
    - https://cdn.bootcdn.net/ajax/libs/raphael/2.3.0/raphael.js
    - https://cdn.bootcdn.net/ajax/libs/underscore.js/1.13.1/underscore-esm-min.js
    - https://cdn.bootcdn.net/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
    - https://cdn.bootcdn.net/ajax/libs/flowchart/1.15.0/flowchart.min.js
    - assets/js/umlconvert.js

    
# 底部额外信息
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dxslin/SlinNotes


markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
        custom_fences: [
            {name: flow, class: uml-flowchart}
           ,{name: sequence, class: uml-sequence-diagram}
           ,{name: mermaid, class: mermaid}
        ]
  - pymdownx.details
  - admonition
  - attr_list

plugins:
  - search
  - git-revision-date-localized:
      type: date

copyright: Copyright &copy; 2021 <a href="https://https://github.com/dxslin">dxslin</a>.